"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .person import *

__all__ = ["Person","PersonEmployment","PersonFacebook","PersonGeo","PersonGithub","PersonGoogleplus","PersonGravatar","PersonGravatarAvatars","PersonGravatarUrls","PersonLinkedin","PersonName","PersonTwitter"]
